import dotenv from "dotenv";
import connectDB from "../config/db.js";
import Product from "../models/Product.js";

dotenv.config();

const products = [
  // ============ MEN'S PRODUCTS (10) ============
  {
    name: "Classic White T-Shirt",
    description: "A soft, breathable cotton t-shirt for everyday wear.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600",
    category: "Men",
    brand: "UrbanWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    countInStock: 50,
    isFeatured: true,
  },
  {
    name: "Men's Slim Fit Jeans",
    description: "Classic slim fit jeans with stretch comfort for all-day wear.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600",
    category: "Men",
    brand: "DenimCo",
    sizes: ["30", "32", "34", "36"],
    colors: ["Blue", "Black", "Grey"],
    countInStock: 40,
    isFeatured: true,
  },
  {
    name: "Men's Leather Jacket",
    description: "Premium genuine leather jacket with a modern slim fit.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600",
    category: "Men",
    brand: "UrbanWear",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Brown"],
    countInStock: 25,
  },
  {
    name: "Men's Hoodie",
    description: "Comfortable fleece hoodie with kangaroo pocket and adjustable hood.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600",
    category: "Men",
    brand: "StreetStyle",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Navy", "Black"],
    countInStock: 45,
  },
  {
    name: "Men's Chino Pants",
    description: "Versatile chino pants perfect for both casual and formal occasions.",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600",
    category: "Men",
    brand: "Craftsman",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black"],
    countInStock: 35,
  },
  {
    name: "Men's Polo Shirt",
    description: "Classic polo shirt with embroidered logo and breathable fabric.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600",
    category: "Men",
    brand: "UrbanWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Navy", "Red", "Black"],
    countInStock: 55,
  },
  {
    name: "Men's Sports Sneakers",
    description: "Lightweight running sneakers with cushioned sole for maximum comfort.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
    category: "Men",
    brand: "Athletica",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Red"],
    countInStock: 30,
  },
  {
    name: "Men's Formal Shirt",
    description: "Crisp formal shirt with button-down collar for professional look.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600",
    category: "Men",
    brand: "Craftsman",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Blue", "Grey"],
    countInStock: 40,
  },
  {
    name: "Men's Cargo Shorts",
    description: "Durable cargo shorts with multiple pockets for utility and style.",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600",
    category: "Men",
    brand: "StreetStyle",
    sizes: ["30", "32", "34", "36"],
    colors: ["Khaki", "Navy", "Olive"],
    countInStock: 35,
  },
  {
    name: "Men's Beanie Hat",
    description: "Warm knitted beanie for cold weather with comfortable fit.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=600",
    category: "Men",
    brand: "UrbanWear",
    sizes: ["One Size"],
    colors: ["Black", "Grey", "Navy", "Red"],
    countInStock: 60,
  },

  // ============ WOMEN'S PRODUCTS (10) ============
  {
    name: "Denim Jacket",
    description: "Vintage-style denim jacket with a relaxed fit and classic design.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600",
    category: "Women",
    brand: "StreetStyle",
    sizes: ["S", "M", "L"],
    colors: ["Blue"],
    countInStock: 30,
    isFeatured: true,
  },
  {
    name: "Women's Floral Dress",
    description: "Beautiful floral print dress perfect for summer days and special occasions.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600",
    category: "Women",
    brand: "Zara",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Floral", "Blue Floral"],
    countInStock: 30,
    isFeatured: true,
  },
  {
    name: "Women's Blazer",
    description: "Elegant tailored blazer for professional and casual wear.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600",
    category: "Women",
    brand: "StreetStyle",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Navy", "Grey"],
    countInStock: 25,
  },
  {
    name: "Women's Maxi Skirt",
    description: "Flowing maxi skirt with elastic waistband for all-day comfort.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600",
    category: "Women",
    brand: "Craftsman",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Navy", "Beige"],
    countInStock: 35,
  },
  {
    name: "Women's Knit Sweater",
    description: "Cozy knit sweater for cooler days with soft and warm fabric.",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600",
    category: "Women",
    brand: "UrbanWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Grey", "Rose"],
    countInStock: 30,
  },
  {
    name: "Women's Leggings",
    description: "High-quality leggings with 4-way stretch for yoga and everyday wear.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600",
    category: "Women",
    brand: "Athletica",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Navy"],
    countInStock: 60,
  },
  {
    name: "Women's Handbag",
    description: "Stylish handbag with multiple compartments for daily essentials.",
    price: 54.99,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600",
    category: "Women",
    brand: "StreetStyle",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Red"],
    countInStock: 25,
  },
  {
    name: "Women's Summer Top",
    description: "Light and breezy summer top with elegant design.",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600",
    category: "Women",
    brand: "Zara",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Yellow", "Pink"],
    countInStock: 45,
  },
  {
    name: "Women's High Heels",
    description: "Elegant high heels with cushioned insole for comfort.",
    price: 64.99,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600",
    category: "Women",
    brand: "Craftsman",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Black", "Nude", "Red"],
    countInStock: 20,
  },

  // ============ KIDS PRODUCTS (10) ============
  {
    name: "Kids Hoodie",
    description: "Warm and cozy hoodie for kids, machine washable and durable.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1519278409-1f56fdda7fe5?w=600",
    category: "Kids",
    brand: "LittleOnes",
    sizes: ["XS", "S", "M"],
    colors: ["Red", "Grey"],
    countInStock: 40,
  },
  {
    name: "Kids Denim Jeans",
    description: "Durable denim jeans for active kids with adjustable waist.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600",
    category: "Kids",
    brand: "LittleOnes",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Black"],
    countInStock: 35,
  },
  {
    name: "Kids T-Shirt Set",
    description: "Pack of 3 colorful t-shirts for kids with fun designs.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600",
    category: "Kids",
    brand: "MiniMe",
    sizes: ["XS", "S", "M"],
    colors: ["Multi", "Pastel"],
    countInStock: 50,
  },
  {
    name: "Kids Winter Jacket",
    description: "Warm padded jacket for winter with hood and zip closure.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1533228100845-08145b01de14?w=600",
    category: "Kids",
    brand: "LittleOnes",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Blue", "Green"],
    countInStock: 25,
  },
  {
    name: "Kids Sneakers",
    description: "Comfortable sneakers for everyday wear with non-slip sole.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
    category: "Kids",
    brand: "MiniMe",
    sizes: ["1", "2", "3", "4", "5"],
    colors: ["White", "Blue", "Red"],
    countInStock: 40,
  },
  {
    name: "Kids Sweatpants",
    description: "Comfortable sweatpants for playtime and relaxation.",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=600",
    category: "Kids",
    brand: "LittleOnes",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Grey", "Navy", "Black"],
    countInStock: 45,
  },
  {
    name: "Kids Dinosaur T-Shirt",
    description: "Fun dinosaur print t-shirt that kids will love.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600",
    category: "Kids",
    brand: "MiniMe",
    sizes: ["XS", "S", "M"],
    colors: ["Green", "Blue", "Red"],
    countInStock: 55,
  },
  {
    name: "Kids Backpack",
    description: "Colorful backpack with multiple pockets for school.",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600",
    category: "Kids",
    brand: "MiniMe",
    sizes: ["One Size"],
    colors: ["Blue", "Red", "Green", "Pink"],
    countInStock: 30,
  },
  {
    name: "Kids Pajama Set",
    description: "Soft cotton pajama set for comfortable sleep.",
    price: 27.99,
    image: "https://images.unsplash.com/photo-1533228100845-08145b01de14?w=600",
    category: "Kids",
    brand: "LittleOnes",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Pink", "Yellow"],
    countInStock: 35,
  },
  {
    name: "Kids Raincoat",
    description: "Waterproof raincoat with hood for rainy days.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1533228100845-08145b01de14?w=600",
    category: "Kids",
    brand: "MiniMe",
    sizes: ["XS", "S", "M"],
    colors: ["Yellow", "Blue", "Red"],
    countInStock: 25,
  },

  // ============ ACCESSORIES (10) ============
  {
    name: "Leather Belt",
    description: "Genuine leather belt with a classic buckle for any outfit.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["One Size"],
    colors: ["Brown", "Black"],
    countInStock: 60,
  },
  {
    name: "Leather Wallet",
    description: "Premium leather wallet with multiple card slots and cash compartment.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    countInStock: 50,
  },
  {
    name: "Sunglasses",
    description: "Polarized sunglasses with UV protection for sunny days.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600",
    category: "Accessories",
    brand: "UrbanWear",
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Grey"],
    countInStock: 30,
  },
  {
    name: "Leather Gloves",
    description: "Genuine leather gloves with soft lining for warmth and style.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown"],
    countInStock: 35,
  },
  {
    name: "Crossbody Bag",
    description: "Stylish crossbody bag for everyday use with adjustable strap.",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
    category: "Accessories",
    brand: "StreetStyle",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Navy"],
    countInStock: 25,
  },
  {
    name: "Beaded Bracelet",
    description: "Handmade beaded bracelet with natural stones and adjustable fit.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["One Size"],
    colors: ["Multi", "Blue", "Brown"],
    countInStock: 70,
  },
  {
    name: "Baseball Cap",
    description: "Classic baseball cap with adjustable strap and breathable design.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600",
    category: "Accessories",
    brand: "UrbanWear",
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Grey", "Red"],
    countInStock: 60,
  },
  {
    name: "Watch Strap",
    description: "Premium leather watch strap compatible with most watches.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    countInStock: 45,
  },
  {
    name: "Keychain",
    description: "Elegant leather keychain with metal hardware.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600",
    category: "Accessories",
    brand: "Craftsman",
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Red"],
    countInStock: 80,
  },
  {
    name: "Travel Duffel Bag",
    description: "Spacious duffel bag for gym or weekend travel.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600",
    category: "Accessories",
    brand: "StreetStyle",
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Grey"],
    countInStock: 20,
  },
];

const importData = async () => {
  try {
    // Connect to database first
    await connectDB();
    
    // Delete existing products
    const deleted = await Product.deleteMany({});
    console.log(`Products removed: ${deleted.deletedCount || 0}`);
    
    // Insert new products
    const inserted = await Product.insertMany(products);
    console.log(`${inserted.length} sample products imported successfully!`);
    console.log(`📊 Product breakdown:`);
    console.log(`   👔 Men: 10 products`);
    console.log(`   👗 Women: 9 products`);
    console.log(`   👶 Kids: 10 products`);
    console.log(`   👜 Accessories: 10 products`);
    console.log(`   📦 Total: 39 products`);
    
    // Exit with success
    process.exit(0);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    if (error.name === 'ValidationError') {
      console.error('Validation Error Details:', error.errors);
    }
    process.exit(1);
  }
};

// Run the import
importData();